version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: portfolio_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  app:
    build: .
    container_name: backend_portfolio
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo